<?php

// *****************************************************
// *      CREATE CONTENTS GROUP [ COLUMNS > ELEMENTS ]
// *****************************************************

	if( ! function_exists('scm_acf_group_contents') ){
		function scm_acf_group_contents( $title, $location = 'post', $option = false, $operator = '==', $order = 0 ){

			if( !$title || !$location )
				return;

			$locations = ( is_string($location) ? array( array( 'param' => ( !$option ? 'post_type' : 'options_page' ), 'operator' => $operator, 'value' => $location ) ) : $location );

			$id = uniqid('group_');

			$group = array (
				'key' => $id,
				'title' => $title,
				'fields' => array (

					scm_acf_column(),

				),
				'location' => array ( $locations ),
				'menu_order' => $order,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => array (
					0 => 'the_content',
					1 => 'excerpt',
					2 => 'custom_fields',
					3 => 'discussion',
					4 => 'comments',
					5 => 'revisions',
					6 => 'slug',
					7 => 'author',
					8 => 'format',
					9 => 'page_attributes',
					10 => 'featured_image',
					11 => 'categories',
					12 => 'tags',
					13 => 'send-trackbacks',
				),
			);

            //if( !file_exists( SCM_DIR_ACF_JSON . $id . '.json' ) ){
	            $fp = fopen( SCM_DIR_ACF_JSON . $id . '.json', 'w');
				fwrite($fp, json_encode($group, JSON_PRETTY_PRINT));
				fclose($fp);
				/*return true;
			}else{
				return false;
			}*/
		}
	}

// *****************************************************
// *      CREATE COLUMS FLEXIBLE CONTENT
// *****************************************************

	if( ! function_exists('scm_acf_column') ){
		function scm_acf_column(){
			$column = array (
				'key' => uniqid('field_'),
				'label' => 'Colonne',
				'name' => 'columns_repeater',
				'prefix' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'button_label' => 'Aggiungi Colonna',
				'min' => '',
				'max' => '',
				'layout' => 'block',
				'sub_fields' => array(
					scm_acf_columns_list(),
					scm_acf_elements(),
				)
			);

			return $column;
		}
	}

	// *****************************************************
	// *      CREATE COLUMS FLEXIBLE LAYOUTS [ > ELEMENTS ]
	// *****************************************************

		if( ! function_exists('scm_acf_columns_list') ){
			function scm_acf_columns_list(){

				$columns_list = array (
					'key' => uniqid('field_'),
					'name' => 'select_columns_width',
					'label' => 'Larghezza',
					'prefix' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
					),
					'default_value' => array (
						'text' => 'text',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				);

				return $columns_list;

			}
		}

// *****************************************************
// *      CREATE ELEMENTS FLEXIBLE CONTENT
// *****************************************************

	if( ! function_exists('scm_acf_elements') ){
		function scm_acf_elements( $elements = array() ){
			$elements = array (
				'key' => uniqid('field_'),
				'label' => 'Componi',
				'name' => 'flexible_build',
				'prefix' => '',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'button_label' => 'Aggiungi Contenuto',
				'min' => '',
				'max' => '',
				'layouts' => array(

					scm_acf_element_image_full(),
					scm_acf_element_image(),
					scm_acf_element_icon(),
					scm_acf_element_title(),
					scm_acf_element_text(),
					scm_acf_element_galleria(),
					scm_acf_element_soggetto(),
					scm_acf_element_module(),
					scm_acf_element_wpcf7(),
					scm_acf_element_login(),

				)
			);

			return $elements;
		}
	}

// *****************************************************
// *      CREATE ELEMENTS FLEXIBLE LAYOUTS
// *****************************************************

	// GALLERIA => [ GALLERIA ] + COMPONI

	if( ! function_exists('scm_acf_element_galleria') ){
		function scm_acf_element_galleria(){
			$type = uniqid('field_');
			$galleria = array (
				'key' => uniqid(),
				'name' => 'galleria_element',
				'label' => 'Galleria',
				'display' => 'block',
				'sub_fields' => array (
					array (
						'key' => uniqid('field_'),
						'label' => 'Seleziona Galleria',
						'name' => 'select_galleria',
						'prefix' => '',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => 100,
							'class' => '',
							'id' => '',
						),
						'post_type' => array (
							0 => 'scm-gallerie',
						),
						'taxonomy' => '',
						'allow_null' => 0,
						'multiple' => 0,
						'return_format' => 'object',
						'ui' => 1,
					),
					array (
						'key' => uniqid('field_'),
						'label' => 'Immagine iniziale',
						'name' => 'module_galleria_init',
						'prefix' => '',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 0,
						'placeholder' => 0,
						'prepend' => '',
						'append' => '',
						'min' => 0,
						'max' => '',
						'step' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => $type,
						'label' => 'Pulsante',
						'name' => 'module_galleria_type',
						'prefix' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => 16,
							'class' => '',
							'id' => '',
						),
						'choices' => array (
							'img' => 'Immagine',
							'txt' => 'Testo',
							'module' => 'Modulo',
						),
						'default_value' => array (
							'img' => 'img',
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'disabled' => 0,
						'readonly' => 0,
					),
					array (
						'key' => uniqid('field_'),
						'label' => 'Numero Immagine',
						'name' => 'module_galleria_img_num',
						'prefix' => '',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array (
							array (
								array (
									'field' => $type,
									'operator' => '==',
									'value' => 'img',
								),
							),
						),
						'wrapper' => array (
							'width' => 16,
							'class' => '',
							'id' => '',
						),
						'default_value' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => 0,
						'max' => '',
						'step' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => uniqid('field_'),
						'label' => 'Dimensione Immagine',
						'name' => 'module_galleria_img_size',
						'prefix' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array (
							array (
								array (
									'field' => $type,
									'operator' => '==',
									'value' => 'img',
								),
							),
						),
						'wrapper' => array (
							'width' => 16,
							'class' => '',
							'id' => '',
						),
						'default_value' => '150px',
						'placeholder' => '150px',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => uniqid('field_'),
						'label' => 'Testo Pulsante',
						'name' => 'module_galleria_txt',
						'prefix' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array (
							array (
								array (
									'field' => $type,
									'operator' => '==',
									'value' => 'txt',
								),
							),
						),
						'wrapper' => array (
							'width' => 16,
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Galleria',
						'placeholder' => 'Galleria',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => uniqid('field_'),
						'label' => 'Sfondo Pulsante',
						'name' => 'module_galleria_txt_bg',
						'prefix' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array (
							array (
								array (
									'field' => $type,
									'operator' => '==',
									'value' => 'txt',
								),
							),
						),
						'wrapper' => array (
							'width' => 52,
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => uniqid('field_'),
						'label' => 'Modulo',
						'name' => 'module_galleria_module',
						'prefix' => '',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array (
							array (
								array (
									'field' => $type,
									'operator' => '==',
									'value' => 'module',
								),
							),
						),
						'wrapper' => array (
							'width' => 52,
							'class' => '',
							'id' => '',
						),
						'post_type' => array (
							0 => 'scm-modules',
						),
						'taxonomy' => '',
						'allow_null' => 0,
						'multiple' => 0,
						'return_format' => 'object',
						'ui' => 1,
					),
				),
				'min' => '',
				'max' => '',
			);
			return $galleria;
		}
	}

	// SOGGETTO => [ SOGGETTO ] + COMPONI

	if( ! function_exists('scm_acf_element_soggetto') ){
		function scm_acf_element_soggetto(){
			$type = uniqid('field_');
			$soggetto = array (
				'key' => uniqid(),
				'name' => 'soggetto_element',
				'label' => 'Soggetto',
				'display' => 'block',
				'sub_fields' => array (
					array (
						'key' => uniqid('field_'),
						'label' => 'Seleziona Soggetto',
						'name' => 'select_soggetto',
						'prefix' => '',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => 100,
							'class' => '',
							'id' => '',
						),
						'post_type' => array (
							0 => 'scm-soggetti',
						),
						'taxonomy' => '',
						'allow_null' => 0,
						'multiple' => 0,
						'return_format' => 'object',
						'ui' => 1,
					),
					array (
						'key' => uniqid('field_'),
						'label' => 'Componi Soggetto',
						'name' => 'flexible_soggetto',
						'prefix' => '',
						'type' => 'flexible_content',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => 100,
							'class' => '',
							'id' => '',
						),
						'button_label' => 'Aggiungi Elemento',
						'min' => '',
						'max' => '',
						'layouts' => array (
							array (
								'key' => uniqid(),
								'name' => 'logo',
								'label' => 'Logo',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => uniqid('field_'),
										'label' => 'Negativo',
										'name' => 'negativo',
										'prefix' => '',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => 50,
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 0,
									),
									array (
										'key' => uniqid('field_'),
										'label' => 'Larghezza',
										'name' => 'larghezza',
										'prefix' => '',
										'type' => 'number',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => 50,
											'class' => '',
											'id' => '',
										),
										'default_value' => 100,
										'placeholder' => 100,
										'prepend' => '',
										'append' => '%',
										'min' => '',
										'max' => '',
										'step' => '',
										'readonly' => 0,
										'disabled' => 0,
									),
								),
								'min' => '',
								'max' => '',
							),
							array (
								'key' => uniqid(),
								'name' => 'map',
								'label' => 'Mappa',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => uniqid('field_'),
										'label' => 'Larghezza',
										'name' => 'larghezza',
										'prefix' => '',
										'type' => 'number',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => 100,
											'class' => '',
											'id' => '',
										),
										'default_value' => 100,
										'placeholder' => 100,
										'prepend' => '',
										'append' => '%',
										'min' => 0,
										'max' => '',
										'step' => '',
										'readonly' => 0,
										'disabled' => 0,
									),
								),
								'min' => '',
								'max' => '',
							),
							array (
								'key' => uniqid(),
								'name' => 'data',
								'label' => 'Dati',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => $type,
										'label' => 'Tipo',
										'name' => 'tipo',
										'prefix' => '',
										'type' => 'select',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => 100,
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'address' => 'Indirizzo',
											'num' => 'Numeri',
											'email' => 'Email',
											'link' => 'Link',
										),
										'default_value' => array (
											'address' => 'address',
										),
										'allow_null' => 0,
										'multiple' => 0,
										'ui' => 0,
										'ajax' => 0,
										'placeholder' => '',
										'disabled' => 0,
										'readonly' => 0,
									),
									array (
										'key' => uniqid('field_'),
										'label' => 'Separatore',
										'name' => 'separatore',
										'prefix' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => 25,
											'class' => '',
											'id' => '',
										),
										'default_value' => '—',
										'placeholder' => '—',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
										'readonly' => 0,
										'disabled' => 0,
									),
									array (
										'key' => uniqid('field_'),
										'label' => 'Mostra Icona',
										'name' => 'mostra_icona',
										'prefix' => '',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => 25,
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 0,
									),
									array (
										'key' => uniqid('field_'),
										'label' => 'Mostra Nome',
										'name' => 'mostra_nome',
										'prefix' => '',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => $type,
													'operator' => '!=',
													'value' => 'address',
												),
											),
										),
										'wrapper' => array (
											'width' => 25,
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 1,
									),
									array (
										'key' => uniqid('field_'),
										'label' => 'Larghezza',
										'name' => 'larghezza',
										'prefix' => '',
										'type' => 'number',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => 25,
											'class' => '',
											'id' => '',
										),
										'default_value' => 100,
										'placeholder' => 100,
										'prepend' => '',
										'append' => '%',
										'min' => '',
										'max' => '',
										'step' => '',
										'readonly' => 0,
										'disabled' => 0,
									),
								),
								'min' => '',
								'max' => '',
							),
						),
					),
				),
				'min' => '',
				'max' => '',
			);
			return $soggetto;
		}
	}

	// MODULE => [ MODULE ]

	if( ! function_exists('scm_acf_element_module') ){
		function scm_acf_element_module(){
			$module = array (
				'key' => uniqid(),
				'name' => 'module_element',
				'label' => 'Modulo',
				'display' => 'block',
				'sub_fields' => array (
					array (
						'key' => uniqid('field_'),
						'label' => 'Seleziona Modulo',
						'name' => 'select_module',
						'prefix' => '',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array (
							0 => 'scm-modules',
						),
						'taxonomy' => '',
						'allow_null' => 0,
						'multiple' => 0,
						'return_format' => 'object',
						'ui' => 1,
					),
				),
				'min' => '',
				'max' => '',
			);
			return $module;
		}
	}

	// WPCF7 => [ WPCF7 ]

	if( ! function_exists('scm_acf_element_wpcf7') ){
		function scm_acf_element_wpcf7(){
			$wpcf7 = array (
				'key' => uniqid(),
				'name' => 'contact_form_element',
				'label' => 'Contact Form',
				'display' => 'block',
				'sub_fields' => array (
					array (
						'key' => uniqid('field_'),
						'label' => 'Seleziona Contact Form',
						'name' => 'select_contact_form',
						'prefix' => '',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array (
							0 => 'wpcf7_contact_form',
						),
						'taxonomy' => '',
						'allow_null' => 0,
						'multiple' => 0,
						'return_format' => 'object',
						'ui' => 1,
					),
				),
				'min' => '',
				'max' => '',
			);
			return $wpcf7;
		}
	}

	// LOGIN => [ TITOLO ]

	if( ! function_exists('scm_acf_element_login') ){
		function scm_acf_element_login(){
			$login = array (
				'key' => uniqid(),
				'name' => 'login_form_element',
				'label' => 'Login Form',
				'display' => 'block',
				'sub_fields' => array (
					array (
						'key' => uniqid('field_'),
						'label' => 'Titolo',
						'name' => 'login_form_title',
						'prefix' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Area Privata',
						'placeholder' => 'Area Privata',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
				'min' => '',
				'max' => 1,
			);
			return $login;
		}
	}

	// TITLE => [ TEXT + TAG + ALIGN ]

	if( ! function_exists('scm_acf_element_title') ){
		function scm_acf_element_title(){
			$title = array (
				'key' => uniqid(),
				'name' => 'title_element',
				'label' => 'Titolo',
				'display' => 'block',
				'sub_fields' => array (
					array (
						'key' => uniqid('field_'),
						'label' => 'Inserisci testo',
						'name' => 'testo',
						'prefix' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => 60,
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => uniqid('field_'),
						'label' => 'Tag',
						'name' => 'select_complete_headings',
						'prefix' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => 20,
							'class' => '',
							'id' => '',
						),
						'choices' => array (
							'select_headings_1' => 'Primario',
			        		'select_headings_2' => 'Secondario',
			        		'select_headings_3' => 'Terziario',
							'h1' => 'h1',
							'h2' => 'h2',
							'h3' => 'h3',
							'h4' => 'h4',
							'h5' => 'h5',
							'h6' => 'h6',
							'.h7' => '.h7',
							'.h8' => '.h8',
							'.h9' => '.h9',
							'.h0' => '.h0',
							'strong' => 'strong',
							'div' => 'div',
						),
						'default_value' => array (
							'select_headings_1' => 'Primario',
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'disabled' => 0,
						'readonly' => 0,
					),
					array (
						'key' => uniqid('field_'),
						'label' => 'Allineamento',
						'name' => 'select_txt_alignment_title',
						'prefix' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => 20,
							'class' => '',
							'id' => '',
						),
						'choices' => array (
							'default' => 'Default',
							'left' => 'Sinistra',
							'right' => 'Destra',
							'center' => 'Centrato',
							'justify' => 'Giustificato',
						),
						'default_value' => array (
							'default' => 'Default',
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'disabled' => 0,
						'readonly' => 0,
					),
				),
				'min' => '',
				'max' => '',
			);

			return $title;

		}
	}

	// TEXT => [ CONTENT ]

	if( ! function_exists('scm_acf_element_text') ){
		function scm_acf_element_text(){
			$text = array (
				'key' => uniqid(),
				'name' => 'text_element',
				'label' => 'Testo',
				'display' => 'block',
				'sub_fields' => array (
					array (
						'key' => uniqid('field_'),
						'label' => 'Inserisci il testo',
						'name' => 'testo',
						'prefix' => '',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'visual',
						'toolbar' => 'basic',
						'media_upload' => 1,
					),
				),
				'min' => '',
				'max' => '',
			);
			return $text;
		}
	}

	// IMAGE => [ IMAGE + TYPE [ NORMAL => WIDTH + HEIGHT || SQUARE => SIZE ] + FLOAT ]

	if( ! function_exists('scm_acf_element_image') ){
		function scm_acf_element_image(){
			$type = uniqid('field_');
			$image = array (
				'key' => uniqid(),
				'name' => 'image_element',
				'label' => 'Immagine',
				'display' => 'block',
				'sub_fields' => array (
					array (
						'key' => uniqid('field_'),
						'label' => 'Seleziona un\'immagine',
						'name' => 'immagine',
						'prefix' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => 40,
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'preview_size' => 'large',
						'library' => 'all',
					),
					array (
						'key' => $type,
						'label' => 'Tipo',
						'name' => 'fissa',
						'prefix' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => 15,
							'class' => '',
							'id' => '',
						),
						'choices' => array (
							'norm' => 'Normal',
							'quad' => 'Quadrata',
						),
						'default_value' => array (
							'norm' => 'Normal',
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'disabled' => 0,
						'readonly' => 0,
					),
					array (
						'key' => uniqid('field_'),
						'label' => 'Larghezza',
						'name' => 'larghezza',
						'prefix' => '',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array (
							array (
								array (
									'field' => $type,
									'operator' => '==',
									'value' => 'norm',
								),
							),
						),
						'wrapper' => array (
							'width' => 15,
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'auto',
						'prepend' => '',
						'append' => 'px',
						'min' => '',
						'max' => '',
						'step' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => uniqid('field_'),
						'label' => 'Altezza',
						'name' => 'altezza',
						'prefix' => '',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array (
							array (
								array (
									'field' => $type,
									'operator' => '==',
									'value' => 'norm',
								),
							),
						),
						'wrapper' => array (
							'width' => 15,
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'auto',
						'prepend' => '',
						'append' => 'px',
						'min' => '',
						'max' => '',
						'step' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => uniqid('field_'),
						'label' => 'Dimensione',
						'name' => 'dimensione',
						'prefix' => '',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array (
							array (
								array (
									'field' => $type,
									'operator' => '==',
									'value' => 'quad',
								),
							),
						),
						'wrapper' => array (
							'width' => 30,
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'auto',
						'prepend' => '',
						'append' => 'px',
						'min' => '',
						'max' => '',
						'step' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => uniqid('field_'),
						'label' => 'Float',
						'name' => 'select_float_img',
						'prefix' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => 15,
							'class' => '',
							'id' => '',
						),
						'choices' => array (
							'no' => 'No float',
							'float-left' => 'Sinistra',
							'float-right' => 'Destra',
							'float-center' => 'Centrato',
						),
						'default_value' => array (
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'disabled' => 0,
						'readonly' => 0,
					),
				),
				'min' => '',
				'max' => '',
			);

			return $image;
		}
	}

	// IMAGE FULL => [ IMAGE + HEIGHT ]

	if( ! function_exists('scm_acf_element_image_full') ){
		function scm_acf_element_image_full(){
			$image_full = array (
				'key' => uniqid(),
				'name' => 'full_element',
				'label' => 'Immagine Full',
				'display' => 'block',
				'sub_fields' => array (
					array (
						'key' => uniqid('field_'),
						'label' => 'Seleziona un\'immagine',
						'name' => 'immagine',
						'prefix' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => 80,
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'preview_size' => 'large',
						'library' => 'all',
					),
					array (
						'key' => uniqid('field_'),
						'label' => 'Altezza',
						'name' => 'altezza',
						'prefix' => '',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => 20,
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'auto',
						'prepend' => '',
						'append' => 'px',
						'min' => '',
						'max' => '',
						'step' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
				'min' => '',
				'max' => '',
			);

			return $image_full;
		}
	}
	
	// ICON => [ FA ICON + SIZE + POSITION ]

	if( ! function_exists('scm_acf_element_icon') ){
		function scm_acf_element_icon(){
			$icon = array (
				'key' => uniqid(),
				'name' => 'icon_element',
				'label' => 'Icona',
				'display' => 'row',
				'sub_fields' => array (
					array (
						'key' => uniqid('field_'),
						'label' => 'Seleziona un\'icona',
						'name' => 'icona',
						'prefix' => '',
						'type' => 'font-awesome',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'fa-star',
						'save_format' => 'class',
						'allow_null' => 0,
						'enqueue_fa' => 1,
						'fa_live_preview' => '',
						'choices' => array (
							'fa-adjust' => ' fa-adjust',
							'fa-adn' => ' fa-adn',
							'fa-align-center' => ' fa-align-center',
							'fa-align-justify' => ' fa-align-justify',
							'fa-align-left' => ' fa-align-left',
							'fa-align-right' => ' fa-align-right',
							'fa-ambulance' => ' fa-ambulance',
							'fa-anchor' => ' fa-anchor',
							'fa-android' => ' fa-android',
							'fa-angellist' => ' fa-angellist',
							'fa-angle-double-down' => ' fa-angle-double-down',
							'fa-angle-double-left' => ' fa-angle-double-left',
							'fa-angle-double-right' => ' fa-angle-double-right',
							'fa-angle-double-up' => ' fa-angle-double-up',
							'fa-angle-down' => ' fa-angle-down',
							'fa-angle-left' => ' fa-angle-left',
							'fa-angle-right' => ' fa-angle-right',
							'fa-angle-up' => ' fa-angle-up',
							'fa-apple' => ' fa-apple',
							'fa-archive' => ' fa-archive',
							'fa-area-chart' => ' fa-area-chart',
							'fa-arrow-circle-down' => ' fa-arrow-circle-down',
							'fa-arrow-circle-left' => ' fa-arrow-circle-left',
							'fa-arrow-circle-o-down' => ' fa-arrow-circle-o-down',
							'fa-arrow-circle-o-left' => ' fa-arrow-circle-o-left',
							'fa-arrow-circle-o-right' => ' fa-arrow-circle-o-right',
							'fa-arrow-circle-o-up' => ' fa-arrow-circle-o-up',
							'fa-arrow-circle-right' => ' fa-arrow-circle-right',
							'fa-arrow-circle-up' => ' fa-arrow-circle-up',
							'fa-arrow-down' => ' fa-arrow-down',
							'fa-arrow-left' => ' fa-arrow-left',
							'fa-arrow-right' => ' fa-arrow-right',
							'fa-arrow-up' => ' fa-arrow-up',
							'fa-arrows' => ' fa-arrows',
							'fa-arrows-alt' => ' fa-arrows-alt',
							'fa-arrows-h' => ' fa-arrows-h',
							'fa-arrows-v' => ' fa-arrows-v',
							'fa-asterisk' => ' fa-asterisk',
							'fa-at' => ' fa-at',
							'fa-backward' => ' fa-backward',
							'fa-ban' => ' fa-ban',
							'fa-bar-chart' => ' fa-bar-chart',
							'fa-barcode' => ' fa-barcode',
							'fa-bars' => ' fa-bars',
							'fa-beer' => ' fa-beer',
							'fa-behance' => ' fa-behance',
							'fa-behance-square' => ' fa-behance-square',
							'fa-bell' => ' fa-bell',
							'fa-bell-o' => ' fa-bell-o',
							'fa-bell-slash' => ' fa-bell-slash',
							'fa-bell-slash-o' => ' fa-bell-slash-o',
							'fa-bicycle' => ' fa-bicycle',
							'fa-binoculars' => ' fa-binoculars',
							'fa-birthday-cake' => ' fa-birthday-cake',
							'fa-bitbucket' => ' fa-bitbucket',
							'fa-bitbucket-square' => ' fa-bitbucket-square',
							'fa-bold' => ' fa-bold',
							'fa-bolt' => ' fa-bolt',
							'fa-bomb' => ' fa-bomb',
							'fa-book' => ' fa-book',
							'fa-bookmark' => ' fa-bookmark',
							'fa-bookmark-o' => ' fa-bookmark-o',
							'fa-briefcase' => ' fa-briefcase',
							'fa-btc' => ' fa-btc',
							'fa-bug' => ' fa-bug',
							'fa-building' => ' fa-building',
							'fa-building-o' => ' fa-building-o',
							'fa-bullhorn' => ' fa-bullhorn',
							'fa-bullseye' => ' fa-bullseye',
							'fa-bus' => ' fa-bus',
							'fa-calculator' => ' fa-calculator',
							'fa-calendar' => ' fa-calendar',
							'fa-calendar-o' => ' fa-calendar-o',
							'fa-camera' => ' fa-camera',
							'fa-camera-retro' => ' fa-camera-retro',
							'fa-car' => ' fa-car',
							'fa-caret-down' => ' fa-caret-down',
							'fa-caret-left' => ' fa-caret-left',
							'fa-caret-right' => ' fa-caret-right',
							'fa-caret-square-o-down' => ' fa-caret-square-o-down',
							'fa-caret-square-o-left' => ' fa-caret-square-o-left',
							'fa-caret-square-o-right' => ' fa-caret-square-o-right',
							'fa-caret-square-o-up' => ' fa-caret-square-o-up',
							'fa-caret-up' => ' fa-caret-up',
							'fa-cc' => ' fa-cc',
							'fa-cc-amex' => ' fa-cc-amex',
							'fa-cc-discover' => ' fa-cc-discover',
							'fa-cc-mastercard' => ' fa-cc-mastercard',
							'fa-cc-paypal' => ' fa-cc-paypal',
							'fa-cc-stripe' => ' fa-cc-stripe',
							'fa-cc-visa' => ' fa-cc-visa',
							'fa-certificate' => ' fa-certificate',
							'fa-chain-broken' => ' fa-chain-broken',
							'fa-check' => ' fa-check',
							'fa-check-circle' => ' fa-check-circle',
							'fa-check-circle-o' => ' fa-check-circle-o',
							'fa-check-square' => ' fa-check-square',
							'fa-check-square-o' => ' fa-check-square-o',
							'fa-chevron-circle-down' => ' fa-chevron-circle-down',
							'fa-chevron-circle-left' => ' fa-chevron-circle-left',
							'fa-chevron-circle-right' => ' fa-chevron-circle-right',
							'fa-chevron-circle-up' => ' fa-chevron-circle-up',
							'fa-chevron-down' => ' fa-chevron-down',
							'fa-chevron-left' => ' fa-chevron-left',
							'fa-chevron-right' => ' fa-chevron-right',
							'fa-chevron-up' => ' fa-chevron-up',
							'fa-child' => ' fa-child',
							'fa-circle' => ' fa-circle',
							'fa-circle-o' => ' fa-circle-o',
							'fa-circle-o-notch' => ' fa-circle-o-notch',
							'fa-circle-thin' => ' fa-circle-thin',
							'fa-clipboard' => ' fa-clipboard',
							'fa-clock-o' => ' fa-clock-o',
							'fa-cloud' => ' fa-cloud',
							'fa-cloud-download' => ' fa-cloud-download',
							'fa-cloud-upload' => ' fa-cloud-upload',
							'fa-code' => ' fa-code',
							'fa-code-fork' => ' fa-code-fork',
							'fa-codepen' => ' fa-codepen',
							'fa-coffee' => ' fa-coffee',
							'fa-cog' => ' fa-cog',
							'fa-cogs' => ' fa-cogs',
							'fa-columns' => ' fa-columns',
							'fa-comment' => ' fa-comment',
							'fa-comment-o' => ' fa-comment-o',
							'fa-comments' => ' fa-comments',
							'fa-comments-o' => ' fa-comments-o',
							'fa-compass' => ' fa-compass',
							'fa-compress' => ' fa-compress',
							'fa-copyright' => ' fa-copyright',
							'fa-credit-card' => ' fa-credit-card',
							'fa-crop' => ' fa-crop',
							'fa-crosshairs' => ' fa-crosshairs',
							'fa-css3' => ' fa-css3',
							'fa-cube' => ' fa-cube',
							'fa-cubes' => ' fa-cubes',
							'fa-cutlery' => ' fa-cutlery',
							'fa-database' => ' fa-database',
							'fa-delicious' => ' fa-delicious',
							'fa-desktop' => ' fa-desktop',
							'fa-deviantart' => ' fa-deviantart',
							'fa-digg' => ' fa-digg',
							'fa-dot-circle-o' => ' fa-dot-circle-o',
							'fa-download' => ' fa-download',
							'fa-dribbble' => ' fa-dribbble',
							'fa-dropbox' => ' fa-dropbox',
							'fa-drupal' => ' fa-drupal',
							'fa-eject' => ' fa-eject',
							'fa-ellipsis-h' => ' fa-ellipsis-h',
							'fa-ellipsis-v' => ' fa-ellipsis-v',
							'fa-empire' => ' fa-empire',
							'fa-envelope' => ' fa-envelope',
							'fa-envelope-o' => ' fa-envelope-o',
							'fa-envelope-square' => ' fa-envelope-square',
							'fa-eraser' => ' fa-eraser',
							'fa-eur' => ' fa-eur',
							'fa-exchange' => ' fa-exchange',
							'fa-exclamation' => ' fa-exclamation',
							'fa-exclamation-circle' => ' fa-exclamation-circle',
							'fa-exclamation-triangle' => ' fa-exclamation-triangle',
							'fa-expand' => ' fa-expand',
							'fa-external-link' => ' fa-external-link',
							'fa-external-link-square' => ' fa-external-link-square',
							'fa-eye' => ' fa-eye',
							'fa-eye-slash' => ' fa-eye-slash',
							'fa-eyedropper' => ' fa-eyedropper',
							'fa-facebook' => ' fa-facebook',
							'fa-facebook-square' => ' fa-facebook-square',
							'fa-fast-backward' => ' fa-fast-backward',
							'fa-fast-forward' => ' fa-fast-forward',
							'fa-fax' => ' fa-fax',
							'fa-female' => ' fa-female',
							'fa-fighter-jet' => ' fa-fighter-jet',
							'fa-file' => ' fa-file',
							'fa-file-archive-o' => ' fa-file-archive-o',
							'fa-file-audio-o' => ' fa-file-audio-o',
							'fa-file-code-o' => ' fa-file-code-o',
							'fa-file-excel-o' => ' fa-file-excel-o',
							'fa-file-image-o' => ' fa-file-image-o',
							'fa-file-o' => ' fa-file-o',
							'fa-file-pdf-o' => ' fa-file-pdf-o',
							'fa-file-powerpoint-o' => ' fa-file-powerpoint-o',
							'fa-file-text' => ' fa-file-text',
							'fa-file-text-o' => ' fa-file-text-o',
							'fa-file-video-o' => ' fa-file-video-o',
							'fa-file-word-o' => ' fa-file-word-o',
							'fa-files-o' => ' fa-files-o',
							'fa-film' => ' fa-film',
							'fa-filter' => ' fa-filter',
							'fa-fire' => ' fa-fire',
							'fa-fire-extinguisher' => ' fa-fire-extinguisher',
							'fa-flag' => ' fa-flag',
							'fa-flag-checkered' => ' fa-flag-checkered',
							'fa-flag-o' => ' fa-flag-o',
							'fa-flask' => ' fa-flask',
							'fa-flickr' => ' fa-flickr',
							'fa-floppy-o' => ' fa-floppy-o',
							'fa-folder' => ' fa-folder',
							'fa-folder-o' => ' fa-folder-o',
							'fa-folder-open' => ' fa-folder-open',
							'fa-folder-open-o' => ' fa-folder-open-o',
							'fa-font' => ' fa-font',
							'fa-forward' => ' fa-forward',
							'fa-foursquare' => ' fa-foursquare',
							'fa-frown-o' => ' fa-frown-o',
							'fa-futbol-o' => ' fa-futbol-o',
							'fa-gamepad' => ' fa-gamepad',
							'fa-gavel' => ' fa-gavel',
							'fa-gbp' => ' fa-gbp',
							'fa-gift' => ' fa-gift',
							'fa-git' => ' fa-git',
							'fa-git-square' => ' fa-git-square',
							'fa-github' => ' fa-github',
							'fa-github-alt' => ' fa-github-alt',
							'fa-github-square' => ' fa-github-square',
							'fa-gittip' => ' fa-gittip',
							'fa-glass' => ' fa-glass',
							'fa-globe' => ' fa-globe',
							'fa-google' => ' fa-google',
							'fa-google-plus' => ' fa-google-plus',
							'fa-google-plus-square' => ' fa-google-plus-square',
							'fa-google-wallet' => ' fa-google-wallet',
							'fa-graduation-cap' => ' fa-graduation-cap',
							'fa-h-square' => ' fa-h-square',
							'fa-hacker-news' => ' fa-hacker-news',
							'fa-hand-o-down' => ' fa-hand-o-down',
							'fa-hand-o-left' => ' fa-hand-o-left',
							'fa-hand-o-right' => ' fa-hand-o-right',
							'fa-hand-o-up' => ' fa-hand-o-up',
							'fa-hdd-o' => ' fa-hdd-o',
							'fa-header' => ' fa-header',
							'fa-headphones' => ' fa-headphones',
							'fa-heart' => ' fa-heart',
							'fa-heart-o' => ' fa-heart-o',
							'fa-history' => ' fa-history',
							'fa-home' => ' fa-home',
							'fa-hospital-o' => ' fa-hospital-o',
							'fa-html5' => ' fa-html5',
							'fa-ils' => ' fa-ils',
							'fa-inbox' => ' fa-inbox',
							'fa-indent' => ' fa-indent',
							'fa-info' => ' fa-info',
							'fa-info-circle' => ' fa-info-circle',
							'fa-inr' => ' fa-inr',
							'fa-instagram' => ' fa-instagram',
							'fa-ioxhost' => ' fa-ioxhost',
							'fa-italic' => ' fa-italic',
							'fa-joomla' => ' fa-joomla',
							'fa-jpy' => ' fa-jpy',
							'fa-jsfiddle' => ' fa-jsfiddle',
							'fa-key' => ' fa-key',
							'fa-keyboard-o' => ' fa-keyboard-o',
							'fa-krw' => ' fa-krw',
							'fa-language' => ' fa-language',
							'fa-laptop' => ' fa-laptop',
							'fa-lastfm' => ' fa-lastfm',
							'fa-lastfm-square' => ' fa-lastfm-square',
							'fa-leaf' => ' fa-leaf',
							'fa-lemon-o' => ' fa-lemon-o',
							'fa-level-down' => ' fa-level-down',
							'fa-level-up' => ' fa-level-up',
							'fa-life-ring' => ' fa-life-ring',
							'fa-lightbulb-o' => ' fa-lightbulb-o',
							'fa-line-chart' => ' fa-line-chart',
							'fa-link' => ' fa-link',
							'fa-linkedin' => ' fa-linkedin',
							'fa-linkedin-square' => ' fa-linkedin-square',
							'fa-linux' => ' fa-linux',
							'fa-list' => ' fa-list',
							'fa-list-alt' => ' fa-list-alt',
							'fa-list-ol' => ' fa-list-ol',
							'fa-list-ul' => ' fa-list-ul',
							'fa-location-arrow' => ' fa-location-arrow',
							'fa-lock' => ' fa-lock',
							'fa-long-arrow-down' => ' fa-long-arrow-down',
							'fa-long-arrow-left' => ' fa-long-arrow-left',
							'fa-long-arrow-right' => ' fa-long-arrow-right',
							'fa-long-arrow-up' => ' fa-long-arrow-up',
							'fa-magic' => ' fa-magic',
							'fa-magnet' => ' fa-magnet',
							'fa-male' => ' fa-male',
							'fa-map-marker' => ' fa-map-marker',
							'fa-maxcdn' => ' fa-maxcdn',
							'fa-meanpath' => ' fa-meanpath',
							'fa-medkit' => ' fa-medkit',
							'fa-meh-o' => ' fa-meh-o',
							'fa-microphone' => ' fa-microphone',
							'fa-microphone-slash' => ' fa-microphone-slash',
							'fa-minus' => ' fa-minus',
							'fa-minus-circle' => ' fa-minus-circle',
							'fa-minus-square' => ' fa-minus-square',
							'fa-minus-square-o' => ' fa-minus-square-o',
							'fa-mobile' => ' fa-mobile',
							'fa-money' => ' fa-money',
							'fa-moon-o' => ' fa-moon-o',
							'fa-music' => ' fa-music',
							'fa-newspaper-o' => ' fa-newspaper-o',
							'fa-openid' => ' fa-openid',
							'fa-outdent' => ' fa-outdent',
							'fa-pagelines' => ' fa-pagelines',
							'fa-paint-brush' => ' fa-paint-brush',
							'fa-paper-plane' => ' fa-paper-plane',
							'fa-paper-plane-o' => ' fa-paper-plane-o',
							'fa-paperclip' => ' fa-paperclip',
							'fa-paragraph' => ' fa-paragraph',
							'fa-pause' => ' fa-pause',
							'fa-paw' => ' fa-paw',
							'fa-paypal' => ' fa-paypal',
							'fa-pencil' => ' fa-pencil',
							'fa-pencil-square' => ' fa-pencil-square',
							'fa-pencil-square-o' => ' fa-pencil-square-o',
							'fa-phone' => ' fa-phone',
							'fa-phone-square' => ' fa-phone-square',
							'fa-picture-o' => ' fa-picture-o',
							'fa-pie-chart' => ' fa-pie-chart',
							'fa-pied-piper' => ' fa-pied-piper',
							'fa-pied-piper-alt' => ' fa-pied-piper-alt',
							'fa-pinterest' => ' fa-pinterest',
							'fa-pinterest-square' => ' fa-pinterest-square',
							'fa-plane' => ' fa-plane',
							'fa-play' => ' fa-play',
							'fa-play-circle' => ' fa-play-circle',
							'fa-play-circle-o' => ' fa-play-circle-o',
							'fa-plug' => ' fa-plug',
							'fa-plus' => ' fa-plus',
							'fa-plus-circle' => ' fa-plus-circle',
							'fa-plus-square' => ' fa-plus-square',
							'fa-plus-square-o' => ' fa-plus-square-o',
							'fa-power-off' => ' fa-power-off',
							'fa-print' => ' fa-print',
							'fa-puzzle-piece' => ' fa-puzzle-piece',
							'fa-qq' => ' fa-qq',
							'fa-qrcode' => ' fa-qrcode',
							'fa-question' => ' fa-question',
							'fa-question-circle' => ' fa-question-circle',
							'fa-quote-left' => ' fa-quote-left',
							'fa-quote-right' => ' fa-quote-right',
							'fa-random' => ' fa-random',
							'fa-rebel' => ' fa-rebel',
							'fa-recycle' => ' fa-recycle',
							'fa-reddit' => ' fa-reddit',
							'fa-reddit-square' => ' fa-reddit-square',
							'fa-refresh' => ' fa-refresh',
							'fa-renren' => ' fa-renren',
							'fa-repeat' => ' fa-repeat',
							'fa-reply' => ' fa-reply',
							'fa-reply-all' => ' fa-reply-all',
							'fa-retweet' => ' fa-retweet',
							'fa-road' => ' fa-road',
							'fa-rocket' => ' fa-rocket',
							'fa-rss' => ' fa-rss',
							'fa-rss-square' => ' fa-rss-square',
							'fa-rub' => ' fa-rub',
							'fa-scissors' => ' fa-scissors',
							'fa-search' => ' fa-search',
							'fa-search-minus' => ' fa-search-minus',
							'fa-search-plus' => ' fa-search-plus',
							'fa-share' => ' fa-share',
							'fa-share-alt' => ' fa-share-alt',
							'fa-share-alt-square' => ' fa-share-alt-square',
							'fa-share-square' => ' fa-share-square',
							'fa-share-square-o' => ' fa-share-square-o',
							'fa-shield' => ' fa-shield',
							'fa-shopping-cart' => ' fa-shopping-cart',
							'fa-sign-in' => ' fa-sign-in',
							'fa-sign-out' => ' fa-sign-out',
							'fa-signal' => ' fa-signal',
							'fa-sitemap' => ' fa-sitemap',
							'fa-skype' => ' fa-skype',
							'fa-slack' => ' fa-slack',
							'fa-sliders' => ' fa-sliders',
							'fa-slideshare' => ' fa-slideshare',
							'fa-smile-o' => ' fa-smile-o',
							'fa-sort' => ' fa-sort',
							'fa-sort-alpha-asc' => ' fa-sort-alpha-asc',
							'fa-sort-alpha-desc' => ' fa-sort-alpha-desc',
							'fa-sort-amount-asc' => ' fa-sort-amount-asc',
							'fa-sort-amount-desc' => ' fa-sort-amount-desc',
							'fa-sort-asc' => ' fa-sort-asc',
							'fa-sort-desc' => ' fa-sort-desc',
							'fa-sort-numeric-asc' => ' fa-sort-numeric-asc',
							'fa-sort-numeric-desc' => ' fa-sort-numeric-desc',
							'fa-soundcloud' => ' fa-soundcloud',
							'fa-space-shuttle' => ' fa-space-shuttle',
							'fa-spinner' => ' fa-spinner',
							'fa-spoon' => ' fa-spoon',
							'fa-spotify' => ' fa-spotify',
							'fa-square' => ' fa-square',
							'fa-square-o' => ' fa-square-o',
							'fa-stack-exchange' => ' fa-stack-exchange',
							'fa-stack-overflow' => ' fa-stack-overflow',
							'fa-star' => ' fa-star',
							'fa-star-half' => ' fa-star-half',
							'fa-star-half-o' => ' fa-star-half-o',
							'fa-star-o' => ' fa-star-o',
							'fa-steam' => ' fa-steam',
							'fa-steam-square' => ' fa-steam-square',
							'fa-step-backward' => ' fa-step-backward',
							'fa-step-forward' => ' fa-step-forward',
							'fa-stethoscope' => ' fa-stethoscope',
							'fa-stop' => ' fa-stop',
							'fa-strikethrough' => ' fa-strikethrough',
							'fa-stumbleupon' => ' fa-stumbleupon',
							'fa-stumbleupon-circle' => ' fa-stumbleupon-circle',
							'fa-subscript' => ' fa-subscript',
							'fa-suitcase' => ' fa-suitcase',
							'fa-sun-o' => ' fa-sun-o',
							'fa-superscript' => ' fa-superscript',
							'fa-table' => ' fa-table',
							'fa-tablet' => ' fa-tablet',
							'fa-tachometer' => ' fa-tachometer',
							'fa-tag' => ' fa-tag',
							'fa-tags' => ' fa-tags',
							'fa-tasks' => ' fa-tasks',
							'fa-taxi' => ' fa-taxi',
							'fa-tencent-weibo' => ' fa-tencent-weibo',
							'fa-terminal' => ' fa-terminal',
							'fa-text-height' => ' fa-text-height',
							'fa-text-width' => ' fa-text-width',
							'fa-th' => ' fa-th',
							'fa-th-large' => ' fa-th-large',
							'fa-th-list' => ' fa-th-list',
							'fa-thumb-tack' => ' fa-thumb-tack',
							'fa-thumbs-down' => ' fa-thumbs-down',
							'fa-thumbs-o-down' => ' fa-thumbs-o-down',
							'fa-thumbs-o-up' => ' fa-thumbs-o-up',
							'fa-thumbs-up' => ' fa-thumbs-up',
							'fa-ticket' => ' fa-ticket',
							'fa-times' => ' fa-times',
							'fa-times-circle' => ' fa-times-circle',
							'fa-times-circle-o' => ' fa-times-circle-o',
							'fa-tint' => ' fa-tint',
							'fa-toggle-off' => ' fa-toggle-off',
							'fa-toggle-on' => ' fa-toggle-on',
							'fa-trash' => ' fa-trash',
							'fa-trash-o' => ' fa-trash-o',
							'fa-tree' => ' fa-tree',
							'fa-trello' => ' fa-trello',
							'fa-trophy' => ' fa-trophy',
							'fa-truck' => ' fa-truck',
							'fa-try' => ' fa-try',
							'fa-tty' => ' fa-tty',
							'fa-tumblr' => ' fa-tumblr',
							'fa-tumblr-square' => ' fa-tumblr-square',
							'fa-twitch' => ' fa-twitch',
							'fa-twitter' => ' fa-twitter',
							'fa-twitter-square' => ' fa-twitter-square',
							'fa-umbrella' => ' fa-umbrella',
							'fa-underline' => ' fa-underline',
							'fa-undo' => ' fa-undo',
							'fa-university' => ' fa-university',
							'fa-unlock' => ' fa-unlock',
							'fa-unlock-alt' => ' fa-unlock-alt',
							'fa-upload' => ' fa-upload',
							'fa-usd' => ' fa-usd',
							'fa-user' => ' fa-user',
							'fa-user-md' => ' fa-user-md',
							'fa-users' => ' fa-users',
							'fa-video-camera' => ' fa-video-camera',
							'fa-vimeo-square' => ' fa-vimeo-square',
							'fa-vine' => ' fa-vine',
							'fa-vk' => ' fa-vk',
							'fa-volume-down' => ' fa-volume-down',
							'fa-volume-off' => ' fa-volume-off',
							'fa-volume-up' => ' fa-volume-up',
							'fa-weibo' => ' fa-weibo',
							'fa-weixin' => ' fa-weixin',
							'fa-wheelchair' => ' fa-wheelchair',
							'fa-wifi' => ' fa-wifi',
							'fa-windows' => ' fa-windows',
							'fa-wordpress' => ' fa-wordpress',
							'fa-wrench' => ' fa-wrench',
							'fa-xing' => ' fa-xing',
							'fa-xing-square' => ' fa-xing-square',
							'fa-yahoo' => ' fa-yahoo',
							'fa-yelp' => ' fa-yelp',
							'fa-youtube' => ' fa-youtube',
							'fa-youtube-play' => ' fa-youtube-play',
							'fa-youtube-square' => ' fa-youtube-square',
						)
					),
					
					array (
						'key' => uniqid('field_'),
						'label' => 'Dimensione',
						'name' => 'dimensione',
						'prefix' => '',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 64,
						'placeholder' => 64,
						'prepend' => '',
						'append' => 'pt',
						'min' => 0,
						'max' => '',
						'step' => 1,
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => uniqid('field_'),
						'label' => 'Posizione',
						'name' => 'select_float_img',
						'prefix' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array (
							'no' => 'No float',
							'float-left' => 'Sinistra',
							'float-right' => 'Destra',
							'float-center' => 'Centrato',
						),
						'default_value' => array (
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'disabled' => 0,
						'readonly' => 0,
					),
				),
				'min' => '',
				'max' => '',
			);

			return $icon;
		}
	}
?>